baseURL = "https://shortdiv.com/"
languageCode = "en-us"
title = "<shortdiv />"
theme = "pickles"
disqusShortname = "shortdiv"


[taxonomies]
  category = "categories"
  tag = "tags"

[params]
  paginate = 5
  twitter = "shortdiv"
  linkedin = "shortdiv"
  feed="/index.xml"
  favicon = "/favicon/favicon.ico"

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

[[menu.main]]
  name = "About"
  url = "/about"
  weight = 2
