baseURL = "http://shortdiv.com/"
languageCode = "en-us"
title = "<shortdiv />"
theme = "pickles"
disableRSS = false
rssLimit = 10

[params]
paginate = 5
twitter = "shortdiv"
linkedin = "shortdiv"
feed="index.xml"
favicon = "/favicon/favicon.ico"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "About"
    url = "/about"
    weight = 2
